### ISSUE TITLE
Add field (or something) for courses to have their own photos

### ISSUE THREAD

**Issue by humayunk** [humayunk/fingo#130]

**Comment by VaedaSolomon** [comment]
![Image](https://github.com/humayunk/fingo/assets/166766412/749904c7-d218-4f6e-861c-5e30e3489d14)
![Image](https://github.com/humayunk/fingo/assets/166766412/5f3be553-5266-4d75-8218-8ef5fc773ff2)
![Image](https://github.com/humayunk/fingo/assets/166766412/3b163d41-43d8-45eb-9182-e28de4f163bf)
