### ISSUE TITLE
Refactor course show page and step lock/unlock logic

### ISSUE THREAD

**Issue by humayunk** [humayunk/fingo#158]
As a user, I can: 

- [ ] See all the lessons on a course page
- [ ] I can only start the first lesson, the others are locked 
- [ ] When I start the first lesson, I am enrolled in a course
- [ ] When I finish a lesson, the subsequent lesson is unlocked 
- [ ] I can enroll in multiple courses

**Comment by juliettehutton** [comment]
Refactored code, used a helper and a partial for that, the lock/unlock thing works, still working on making it appear like on the updated wireframes (with the Start lesson button to enroll in the course + start the user progress
