### ISSUE TITLE
Note: for demo, for Leaderboard to be well populated, will need to have multiple users with different amounts of coins

### ISSUE THREAD

**Issue by VaedaSolomon** [humayunk/fingo#163]
Idea: Ryan (demo dude) + 4 team members (Humayun, Juliette, Vaeda, Jeff). 
Right now leaderboard will pull top 5 users.

**Comment by juliettehutton** [comment]
Currently with 5 users after doing a lesson: 

![Image](https://github.com/humayunk/fingo/assets/166848018/73a7870c-aad2-4028-b0f2-26d948ed0867)
