### ISSUE TITLE
Create dashboard page (controller backend and view)

### ISSUE THREAD

**Issue by humayunk** [humayunk/fingo#66]

**Comment by humayunk** [comment]
![Image](https://github.com/humayunk/fingo/assets/4333374/4b80baf1-535b-4a19-86a0-e2886bca65e8)

**Comment by VaedaSolomon** [comment]
![Image](https://github.com/humayunk/fingo/assets/166766412/335ca905-bdd5-4782-8f0f-500fe9ee51aa)
![Image](https://github.com/humayunk/fingo/assets/166766412/e90b2581-d066-46ca-9ce6-54ae6c423a3a)

**Comment by VaedaSolomon** [comment]
![Image](https://github.com/humayunk/fingo/assets/166766412/ec8abfc3-736a-4429-ac49-3b66dd16b143)
![Image](https://github.com/humayunk/fingo/assets/166766412/cf350bc8-c74f-45b3-ab07-5baccb12fea1)
